# Количество виртуальных машин
replicaCount: 2

# Проект
project:
  create: true
  name: student-lab-v2
  template: student
  resourceQuota:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "5"
      memory: "10Gi"
  administrators:
    - subject: User
      name: test-user

# Образ
image:
  url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img

# Диск
disk:
  name: disk
  size: 3Gi

# Виртуальная машина
vm:
  nodeSelector: []
  namePrefix: student
  cpu: 1
  memory: 2Gi
  virtualMachineClassName: generic
  runPolicy: AlwaysOn

# Cloud-init
cloudInit:
  user: student
  passwordHash: "$6$rounds=4096$ykcmF0DzFvsAPiP.$sXkbiv2V4PjzaOdV4P.LEkAiixLZ/98GFCerGPBmBV9jKM.sulnQSWsAHJHvs7zUIUBmIKgUCbblbSoqktXOn1"
  sshPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILNIo5B2+UzzAc+ixUuJxCdRLeopVmuNW9XqTAfxMMfG admin@DESKTOP-SDN5N3N

# ttyd
ttyd:
  enabled: true
  port: 7681
  password: "student123"

# Ingress
ingress:
  enabled: true
  className: nginx
  hostBase: poligon.cs.vsu.ru
  clusterIssuer: selfsigned
