{{- $vmCount := .Values.replicaCount | int -}}
{{- range $i := until $vmCount }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-init-{{ $.Release.Name }}-{{ $i }}
  namespace: {{ include "student-lab.namespace" $ }}
  labels:
    {{- include "student-lab.labels" $ | nindent 4 }}
type: provisioning.virtualization.deckhouse.io/cloud-init
stringData:
  userData: |
    #cloud-config
    ssh_pwauth: True
    users:
      - name: {{ $.Values.cloudInit.user }}
        passwd: {{ $.Values.cloudInit.passwordHash | quote }}
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: False
    packages:
      - qemu-guest-agent
      {{- if $.Values.ttyd.enabled }}
      - ttyd
      {{- end }}
    runcmd:
      {{- if $.Values.ttyd.enabled }}
      - |
        nohup ttyd --interface 0.0.0.0 --port {{ .Values.ttyd.port }} --credential {{ .Values.cloudInit.user }}:{{ .Values.ttyd.password }} bash > /var/log/ttyd.log 2>&1 &
      {{- end }}
      - systemctl enable qemu-guest-agent --now
---
{{- end }}
