{{- $vmCount := .Values.replicaCount | int -}}
{{- range $i := until $vmCount }}
---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: {{ include "student-lab.vmName" (merge (dict "index" $i) $) }}
  namespace: {{ include "student-lab.namespace" $ }}
  labels:
    {{- include "student-lab.labels" $ | nindent 4 }}
    vm-index: "{{ $i }}"
spec:
  {{- $nodeSelector := index $.Values.vm.nodeSelector $i | default dict }}
  {{- if $nodeSelector }}
  nodeSelector:
    {{- toYaml $nodeSelector | nindent 4 }}
  {{- end }}
  virtualMachineClassName: {{ $.Values.vm.virtualMachineClassName }}
  runPolicy: {{ $.Values.vm.runPolicy }}
  cpu:
    cores: {{ $.Values.vm.cpu }}
  memory:
    size: {{ $.Values.vm.memory }}
  provisioning:
    type: UserDataRef
    userDataRef:
      kind: Secret
      name: cloud-init-{{ $.Release.Name }}-{{ $i }}
  blockDeviceRefs:
    - kind: VirtualDisk
      name: {{ $.Values.disk.name }}-{{ $.Release.Name }}-{{ $i }}
---
{{- end }}
